# Config is being replaced by yaml in SPRING_CONFIG_LOCATION environment variable
logging:
  level:
    com:
      zggis: ${LOGGING_LEVEL:DEBUG}
logfile:
  dir: C:\temp
selenium:
  driver_location: C:\projects\plex-tvtime\drivers\chromedriver.exe
  browser_location: C:\projects\plex-tvtime\browsers\windows\chrome-win64\chrome.exe